// Work Type Types
export interface WorkTypeResponse {
  id: string;
  name: string;
  department: string;
  calculationType: 'hourly' | 'daily' | 'weld_count';
  unitPrice: number;
  createdAt: Date;
  updatedAt: Date;
}

// Work Item Types
export interface WorkItemResponse {
  id: string;
  name: string;
  productCode?: string; // Auto-generated: YYMMSSSIZE (e.g., 260101A)
  size?: string; // A, B, C, D, E, F
  shape?: string; // Tròn, Vuông, Chữ nhật, Khác
  description?: string; // User description
  difficultyLevel: string;
  pricePerWeld: number;
  totalQuantity: number;
  weldsPerItem: number;
  status: 'Tạo mới' | 'Đang sản xuất' | 'Hoàn thành';
  estimatedDeliveryDate?: string;
  quantityMade?: number;
  weight?: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateWorkItemDto {
  // name removed - will be auto-generated by backend
  description?: string; // Optional user description
  shape?: string; // Optional shape selection
  sizes: string[]; // Required: array of sizes (A-F)
  existingSequence?: number; // Optional: add to existing STT instead of creating new
  difficultyLevel: string;
  pricePerWeld: number;
  totalQuantity: number;
  weldsPerItem: number;
  estimatedDeliveryDate?: string;
  weight?: number;
}

export interface UpdateWorkItemDto {
  // name will be auto-regenerated if description or shape changes
  description?: string; // Can update
  shape?: string; // Can update
  // size and productCode cannot be updated (read-only after creation)
  difficultyLevel?: string;
  pricePerWeld?: number;
  totalQuantity?: number;
  weldsPerItem?: number;
  status?: string;
  estimatedDeliveryDate?: string;
  weight?: number;
}

// Work Record Types
export interface WorkRecordResponse {
  id: string;
  employeeId: string;
  employee?: {
    id: string;
    firstName: string;
    lastName: string;
    employeeId: string;
  };
  workDate: string;
  workTypeId: string;
  workType?: {
    id: string;
    name: string;
    calculationType: string;
  };
  workItemId?: string;
  workItem?: {
    id: string;
    name: string;
    difficultyLevel: string;
    weldsPerItem?: number;
  };
  quantity: number;
  unitPrice: number;
  totalAmount: number;
  isOvertime: boolean;
  overtimeQuantity?: number;
  overtimeHours?: number;
  notes?: string;
  status?: 'Tạo mới' | 'Đã thanh toán';
  createdBy: string;
  createdByUser?: {
    id: string;
    firstName: string;
    lastName: string;
  };
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateWorkRecordDto {
  employeeId: string;
  workDate: string;
  workTypeId: string;
  workItemId?: string;
  quantity: number;
  unitPrice?: number;
  isOvertime?: boolean;
  overtimeQuantity?: number;
  overtimeHours?: number;
  notes?: string;
  status?: 'Tạo mới' | 'Đã thanh toán';
}

export interface UpdateWorkRecordDto {
  employeeId?: string;
  workDate?: string;
  workTypeId?: string;
  workItemId?: string;
  quantity?: number;
  unitPrice?: number;
  isOvertime?: boolean;
  overtimeQuantity?: number;
  overtimeHours?: number;
  notes?: string;
  status?: 'Tạo mới' | 'Đã thanh toán';
}

export interface EmployeeProductAggregation {
  employeeId: string;
  employeeName: string;
  workItemId: string;
  workItemName: string;
  calculationType: 'hourly' | 'daily' | 'weld_count';
  totalQuantity: number;
  lastWorkDate?: string;
}

// Monthly Salary Types
export interface MonthlySalaryResponse {
  id: string;
  employeeId: string;
  employee?: {
    id: string;
    firstName: string;
    lastName: string;
    employeeId: string;
  };
  year: number;
  month: number;
  dateFrom?: string;
  dateTo?: string;
  totalWorkDays: number;
  totalAmount: number;
  allowances?: number;
  advancePayment?: number;
  status: 'Tạm tính' | 'Thanh toán';
  paidAt?: string | null;
  calculatedAt?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CalculateMonthlySalaryDto {
  employeeId: string;
  dateFrom: string;
  dateTo: string;
}

// Work Report Types
export interface WorkReport {
  period: string;
  totalEmployees: number;
  totalWorkDays: number;
  totalAmount: number;
  byDepartment: Array<{
    department: string;
    totalAmount: number;
    totalWorkDays: number;
  }>;
  byWorkType: Array<{
    workTypeName: string;
    totalAmount: number;
    count: number;
  }>;
}

/** GET /work/reports/payroll-period — lương chỉ phiếu status Thanh toán + paid_at trong kỳ */
export interface PayrollPeriodReportSummary {
  paidSlipCount: number;
  totalAmountSum: number;
  totalAllowancesSum: number;
  totalAdvanceSum: number;
  totalNetPaid: number;
}

export interface PayrollPeriodPaidSalaryRow {
  id: string;
  employeeId: string;
  employee?: {
    id: string;
    firstName: string;
    lastName: string;
    employeeId: string;
  };
  year: number;
  month: number;
  dateFrom?: string;
  dateTo?: string;
  totalWorkDays: number;
  totalAmount: number;
  allowances: number;
  advancePayment: number;
  status: 'Tạm tính' | 'Thanh toán';
  paidAt: string;
  netPaid: number;
}

export interface PayrollPeriodEmployeeActivityRow {
  employeeId: string;
  firstName: string;
  lastName: string;
  employeeCode: string;
  department: string | null;
  workDays: number;
  /** Tổng số giờ tăng ca (loại theo giờ) */
  overtimeHours: number;
  /** Tổng lượng tăng ca (overtime_quantity, ví dụ SP/mối hàn tăng ca) */
  overtimeQuantity: number;
  /** Số loại sản phẩm (distinct work_item_id trong kỳ, bỏ bản ghi không gắn sản phẩm) */
  productTypeCount: number;
  totalQuantity: number;
}

export interface PayrollPeriodReport {
  periodLabel: string;
  dateFrom: string;
  dateTo: string;
  summary: PayrollPeriodReportSummary;
  paidSalaries: PayrollPeriodPaidSalaryRow[];
  byEmployee: PayrollPeriodEmployeeActivityRow[];
}

export type TopPerformerMetricKey =
  | 'totalQuantity'
  | 'totalAmount'
  | 'productTypeCount'
  | 'workDays'
  | 'overtimeHours'
  | 'overtimeQuantity'
  | 'weekAttendanceRatio';

export interface TopPerformerRankRow {
  rank: number;
  employeeId: string;
  firstName: string;
  lastName: string;
  employeeCode: string;
  department: string | null;
  value: number;
}

export interface TopPerformersReport {
  periodLabel: string;
  dateFrom: string;
  dateTo: string;
  top: number;
  weeksInPeriod: number;
  onlyPaidEmployees: boolean;
  rankings: Partial<Record<TopPerformerMetricKey, TopPerformerRankRow[]>>;
}

// Overtime Config Types
export interface OvertimeConfigResponse {
  id: string;
  workTypeId: string;
  workType?: {
    id: string;
    name: string;
    department: string;
    calculationType: string;
  };
  overtimePricePerWeld: number;
  overtimePercentage: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateOvertimeConfigDto {
  workTypeId: string;
  overtimePricePerWeld?: number;
  overtimePercentage?: number;
}

export interface UpdateOvertimeConfigDto {
  overtimePricePerWeld?: number;
  overtimePercentage?: number;
}

